### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by mtijas** [murtoM/invekotin#23]
Starting app after `make clean` gives `unexpected token u`. Does not start.

Steps to reproduce:
- `make clean`
- `make up`

Error message:
```bash
invekotin-dev | [nodemon] starting `node src/index.js`
invekotin-dev | undefined:1
invekotin-dev | undefined
invekotin-dev | ^
invekotin-dev | 
invekotin-dev | SyntaxError: Unexpected token u in JSON at position 0
invekotin-dev |     at JSON.parse (<anonymous>)
invekotin-dev |     at Object.<anonymous> (/usr/src/app/src/config.js:12:23)
invekotin-dev |     at Module._compile (node:internal/modules/cjs/loader:1099:14)
invekotin-dev |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
invekotin-dev |     at Module.load (node:internal/modules/cjs/loader:975:32)
invekotin-dev |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
invekotin-dev |     at Module.require (node:internal/modules/cjs/loader:999:19)
invekotin-dev |     at require (node:internal/modules/cjs/helpers:102:18)
invekotin-dev |     at Object.<anonymous> (/usr/src/app/src/index.js:9:16)
invekotin-dev |     at Module._compile (node:internal/modules/cjs/loader:1099:14)
invekotin-dev | 
invekotin-dev | Node.js v17.9.0
invekotin-dev | [nodemon] app crashed - waiting for file changes before starting...
```

System: Fedora 35 (Linux fedora 5.16.19-200.fc35.x86_64 #1 SMP PREEMPT), KDE, SELinux enabled.

**Comment by mtijas** [comment]
Oops, .env was wrong and was the cause of this crash. Not an issue.

**Comment by mtijas** [comment]
This seems to actually be an issue. There seems to be some invisible chars in the config
